import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const FACES = [
  { family: "Chicago", upstream: "ChicagoFLF.woff2", vendored: "chicago-flf.woff2" },
  { family: "Chicago_12", upstream: "ChiKareGo2.woff2", vendored: "chikarego2.woff2" },
  {
    family: "Geneva_9",
    upstream: "FindersKeepers.woff2",
    vendored: "finders-keepers.woff2",
  },
  { family: "Monaco", upstream: "monaco.woff2", vendored: "monaco.woff2" },
];

export const SPRITES = ["button.svg", "button-default.svg"];

const FONT_FACE_RULE = /@font-face\{[^}]*\}/g;
const RELATIVE_URL = /url\((["']?)(?!data:|https?:|\/)([^)"']+)\1\)/g;

export function vendorSystemCss(source: string, version: string) {
  const upstreamFaces = source.match(FONT_FACE_RULE) ?? [];

  if (upstreamFaces.length !== FACES.length) {
    throw new Error(
      `@sakun/system.css ${version} declares ${upstreamFaces.length} faces, expected ${FACES.length}`,
    );
  }

  const selfHosted = FACES.map(
    ({ family, vendored }) =>
      `@font-face {\n  font-family: ${family};\n  src: url("/assets/fonts/${vendored}") format("woff2");\n  font-display: block;\n}`,
  ).join("\n\n");
  const body = source
    .replace(FONT_FACE_RULE, "")
    .replace(RELATIVE_URL, 'url("/assets/system/$2")')
    .trim();

  return `/* Generated by scripts/vendor-system-css.ts from @sakun/system.css ${version}. Do not edit. */\n\n${selfHosted}\n\n${body}\n`;
}

export function readUpstream(root: string) {
  const packageRoot = join(root, "node_modules", "@sakun", "system.css");
  const dist = join(packageRoot, "dist");
  const { version } = JSON.parse(
    readFileSync(join(packageRoot, "package.json"), "utf8"),
  ) as { version: string };

  return { dist, version, source: readFileSync(join(dist, "system.css"), "utf8") };
}

if (import.meta.filename === process.argv[1]) {
  const root = join(import.meta.dirname, "..");
  const { dist, version, source } = readUpstream(root);
  const fonts = join(root, "public", "assets", "fonts");
  const sprites = join(root, "public", "assets", "system");

  mkdirSync(fonts, { recursive: true });
  mkdirSync(sprites, { recursive: true });

  for (const face of FACES) {
    copyFileSync(join(dist, face.upstream), join(fonts, face.vendored));
  }

  for (const sprite of SPRITES) {
    copyFileSync(join(dist, sprite), join(sprites, sprite));
  }

  writeFileSync(join(root, "styles", "system.css"), vendorSystemCss(source, version));
  console.log(`Vendored @sakun/system.css ${version}`);
}
